### ISSUE TITLE
python -m synoindexwatcher > NOT WORKING

### ISSUE THREAD

**Issue by danyfire** [chrisjbillington/inotify_simple#25]
Hello,

I keep getting a error after I did the command "python -m synoindexwatcher" can you help me  :
I started doing the installation stuff :

wget https://bootstrap.pypa.io/get-pip.py -qO - | sudo python
sudo python -m pip install --upgrade synoindexwatcher
python -m synoindexwatcher

>>>synoindexwatcher doesn't start I tried with 2 admin accounts :-(
**

_mersaine@Homeland:~$ python -m synoindexwatcher
2020-12-15 20:23:01,638 INFO Adding watch for path: /volume1/music
2020-12-15 20:23:01,639 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 206, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 176, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 110, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 39, in _libc_call
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 2] No such file or directory_

**

Help me please. I don't understand I'm not a expert.
Danyfire

**Comment by danyfire** [comment]
Wrong place don't know how to delete.

**Comment by letorbi** [comment]
Well, i guess this issue should be placed in https://github.com/letorbi/synoindexwatcher ;)

AFAIR this was caused by a regression in *inotify_simple* 1.3.2, which was fixed with version 1.3.3. Please upgrade *inotify_simple* and *inotifyrecursive* to the latest versions with the following commands:

```
sudo python -m pip install --upgrade inotify_simple
sudo python -m pip install --upgrade inotifyrecursive
```

Please create a new issue in my Synoindex Watcher repo, if the problem persists.

**Comment by danyfire** [comment]
Thank you for the quick reply I posted there : https://github.com/letorbi/synoindexwatcher/issues/45
I did the commands you told me, but the problem persist. 
Results in the bug post.
